// Mock data for the Super Admin Dashboard


export const mockOrganizations = [
  {
    id: 'org-owner',
    name: 'Super Admin (Owner)',
    type: 'owner',
    parentId: null,
    gst: 'GST-OWNER-001',
    email: 'owner@superadmin.com',
    phone: '+91 98765 43210',
    status: 'active',
    createdAt: '2024-01-01',
  },
  {
    id: 'org-partner-1',
    name: 'TechVision Partners',
    type: 'partner',
    parentId: 'org-owner',
    gst: '29ABCDE1234F1Z5',
    email: 'admin@techvision.com',
    phone: '+91 98765 11111',
    status: 'active',
    createdAt: '2024-02-15',
    brandColor: '#0d9488',
    tier: 'platinum',
    walletBalance: 500000,
    creditLimit: 1000000,
    customDomain: 'portal.techvision.com',
    commissionRate: 20,
  },
  {
    id: 'org-partner-2',
    name: 'GlobalSoft Solutions',
    type: 'partner',
    parentId: 'org-owner',
    gst: '27FGHIJ5678K2Z3',
    email: 'contact@globalsoft.com',
    phone: '+91 98765 22222',
    status: 'active',
    createdAt: '2024-03-10',
    brandColor: '#0d9488',
    tier: 'gold',
    walletBalance: 250000,
    creditLimit: 500000,
    commissionRate: 15,
  },
  {
    id: 'org-partner-3',
    name: 'InnovateTech Inc',
    type: 'partner',
    parentId: 'org-owner',
    gst: '19KLMNO9012P3Z1',
    email: 'info@innovatetech.com',
    phone: '+91 98765 33333',
    status: 'suspended',
    createdAt: '2024-04-20',
    brandColor: '#f59e0b',
    tier: 'silver',
    walletBalance: -50000,
    creditLimit: 200000,
    commissionRate: 10,
  },
  {
    id: 'org-subpartner-1',
    name: 'Regional Reseller A',
    type: 'subpartner',
    parentId: 'org-partner-1',
    gst: '29QRSTU3456V4Z7',
    email: 'sales@regional-a.com',
    phone: '+91 98765 44444',
    status: 'active',
    createdAt: '2024-05-01',
  },
  {
    id: 'org-subpartner-2',
    name: 'City Sales Hub',
    type: 'subpartner',
    parentId: 'org-partner-1',
    gst: '29WXYZA7890B5Z9',
    email: 'contact@citysales.com',
    phone: '+91 98765 55555',
    status: 'active',
    createdAt: '2024-06-10',
  },
  {
    id: 'org-subpartner-3',
    name: 'Metro Distributors',
    type: 'subpartner',
    parentId: 'org-partner-2',
    gst: '27CDEFG1234H6Z2',
    email: 'admin@metrodist.com',
    phone: '+91 98765 66666',
    status: 'active',
    createdAt: '2024-07-05',
  },
  {
    id: 'org-customer-1',
    name: 'ABC Manufacturing Ltd',
    type: 'customer',
    parentId: 'org-subpartner-1',
    gst: '29IJKLM5678N7Z4',
    email: 'it@abcmfg.com',
    phone: '+91 98765 77777',
    status: 'active',
    createdAt: '2024-08-01',
  },
  {
    id: 'org-customer-2',
    name: 'XYZ Retail Chain',
    type: 'customer',
    parentId: 'org-subpartner-2',
    gst: '29OPQRS9012T8Z6',
    email: 'tech@xyzretail.com',
    phone: '+91 98765 88888',
    status: 'active',
    createdAt: '2024-08-15',
  },
  {
    id: 'org-customer-3',
    name: 'Global Logistics Co',
    type: 'customer',
    parentId: 'org-subpartner-3',
    gst: '27UVWXY3456Z9Z8',
    email: 'systems@globallog.com',
    phone: '+91 98765 99999',
    status: 'active',
    createdAt: '2024-09-01',
  },
];

export const mockPlans = [
  {
    id: 'plan-basic',
    name: 'Basic Plan',
    description: 'Essential features for small teams',
    pricePerSeat: 499,
    features: ['Order Management', 'Basic Reports', 'Email Support', 'Up to 500 users'],
    billingCycle: 'monthly',
    trial: true,
    gracePeriod: 7,
  },
  {
    id: 'plan-premium',
    name: 'Premium Plan',
    description: 'Advanced features for growing businesses',
    pricePerSeat: 999,
    features: ['Advanced Analytics', 'API Access', 'Priority Support', 'Custom Branding', 'Up to 2,000 users'],
    billingCycle: 'monthly',
    trial: true,
    gracePeriod: 14,
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise Plan',
    description: 'Complete solution for large organizations',
    pricePerSeat: 1499,
    features: ['Unlimited Users', 'White-Label', 'Dedicated Support', 'SLA Guarantee', 'Custom Integrations', 'Dedicated Account Manager'],
    billingCycle: 'annual',
    trial: false,
    gracePeriod: 30,
  },
];

export const mockSubscriptions = [
  {
    id: 'sub-1',
    organizationId: 'org-partner-1',
    planId: 'plan-enterprise',
    planName: 'Enterprise Plan',
    status: 'active',
    seatsPurchased: 2000,
    seatsAllocated: 1650,
    seatsActivated: 1420,
    startDate: '2024-02-15',
    endDate: '2025-02-14',
    price: 2998000,
    autoRenew: true,
  },
  {
    id: 'sub-2',
    organizationId: 'org-partner-2',
    planId: 'plan-premium',
    planName: 'Premium Plan',
    status: 'active',
    seatsPurchased: 1500,
    seatsAllocated: 980,
    seatsActivated: 850,
    startDate: '2024-03-10',
    endDate: '2025-03-09',
    price: 1498500,
    autoRenew: true,
  },
  {
    id: 'sub-3',
    organizationId: 'org-partner-3',
    planId: 'plan-basic',
    planName: 'Basic Plan',
    status: 'suspended',
    seatsPurchased: 500,
    seatsAllocated: 500,
    seatsActivated: 320,
    startDate: '2024-04-20',
    endDate: '2025-04-19',
    price: 249500,
    autoRenew: false,
  },
  {
    id: 'sub-4',
    organizationId: 'org-subpartner-1',
    planId: 'plan-enterprise',
    planName: 'Enterprise Plan',
    status: 'active',
    seatsPurchased: 800,
    seatsAllocated: 650,
    seatsActivated: 580,
    startDate: '2024-05-01',
    endDate: '2025-04-30',
    price: 1199200,
    autoRenew: true,
  },
  {
    id: 'sub-5',
    organizationId: 'org-subpartner-2',
    planId: 'plan-premium',
    planName: 'Premium Plan',
    status: 'active',
    seatsPurchased: 600,
    seatsAllocated: 520,
    seatsActivated: 480,
    startDate: '2024-06-10',
    endDate: '2025-06-09',
    price: 599400,
    autoRenew: true,
  },
];

export const mockEndUsers = [
  ...Array.from({ length: 50 }, (_, i) => ({
    id: `user-${i + 1}`,
    name: `User ${i + 1}`,
    email: `user${i + 1}@customer.com`,
    organizationId: i % 3 === 0 ? 'org-customer-1' : i % 3 === 1 ? 'org-customer-2' : 'org-customer-3',
    subscriptionId: i % 3 === 0 ? 'sub-4' : 'sub-5',
    state: i % 10 === 0 ? 'suspended' : i % 8 === 0 ? 'allocated' : 'activated',
    activatedAt: i % 8 === 0 ? null : new Date(2024, 7 + Math.floor(i / 10), i % 28 + 1).toISOString(),
    lastLogin: i % 8 === 0 ? null : new Date(2024, 9, 26 - (i % 26)).toISOString(),
    idleDays: i % 8 === 0 ? 0 : i % 26,
  })),
];

export const mockAuditEvents = [
  {
    id: 'audit-1',
    timestamp: '2024-10-26T10:30:00Z',
    actor: 'admin@superadmin.com',
    actorRole: 'Super Admin',
    action: 'Created Partner',
    scope: 'TechVision Partners',
    details: 'New partner organization created with 2000 seats',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-2',
    timestamp: '2024-10-26T09:15:00Z',
    actor: 'admin@techvision.com',
    actorRole: 'Partner Admin',
    action: 'Allocated Seats',
    scope: 'Regional Reseller A',
    details: 'Allocated 800 seats to sub-partner',
    ipAddress: '203.45.67.89',
  },
  {
    id: 'audit-3',
    timestamp: '2024-10-26T08:45:00Z',
    actor: 'admin@superadmin.com',
    actorRole: 'Super Admin',
    action: 'Suspended Organization',
    scope: 'InnovateTech Inc',
    details: 'Suspended due to payment overdue',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-4',
    timestamp: '2024-10-25T16:20:00Z',
    actor: 'sales@regional-a.com',
    actorRole: 'Sub-Partner Admin',
    action: 'Activated User',
    scope: 'ABC Manufacturing Ltd',
    details: 'Activated 50 new end-user licenses',
    ipAddress: '110.22.33.44',
  },
  {
    id: 'audit-5',
    timestamp: '2024-10-25T14:10:00Z',
    actor: 'admin@superadmin.com',
    actorRole: 'Super Admin',
    action: 'Created Private Offer',
    scope: 'GlobalSoft Solutions',
    details: 'Custom pricing: ₹899/seat for 1500 seats',
    ipAddress: '192.168.1.100',
  },
];

export const mockTickets = [
  {
    id: 'ticket-1',
    organizationId: 'org-partner-1',
    subject: 'Unable to allocate seats to sub-partner',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2024-10-25T10:00:00Z',
    assignedTo: 'Support Team A',
  },
  {
    id: 'ticket-2',
    organizationId: 'org-customer-2',
    subject: 'Billing discrepancy in last invoice',
    status: 'open',
    priority: 'medium',
    createdAt: '2024-10-24T14:30:00Z',
    assignedTo: null,
  },
  {
    id: 'ticket-3',
    organizationId: 'org-subpartner-1',
    subject: 'Request for custom branding setup',
    status: 'resolved',
    priority: 'low',
    createdAt: '2024-10-20T09:15:00Z',
    assignedTo: 'Support Team B',
  },
];

export const mockInvoices = [
  {
    id: 'inv-001',
    organizationId: 'org-partner-1',
    amount: 2998000,
    dueDate: '2024-11-15',
    status: 'pending',
    items: [
      { description: 'Enterprise Plan - 2000 users @ ₹1,499/user', quantity: 2000, price: 1499 },
    ],
  },
  {
    id: 'inv-002',
    organizationId: 'org-partner-2',
    amount: 1498500,
    dueDate: '2024-11-10',
    status: 'paid',
    items: [
      { description: 'Premium Plan - 1500 users @ ₹999/user', quantity: 1500, price: 999 },
    ],
  },
  {
    id: 'inv-003',
    organizationId: 'org-partner-3',
    amount: 249500,
    dueDate: '2024-10-20',
    status: 'overdue',
    items: [
      { description: 'Basic Plan - 500 users @ ₹499/user', quantity: 500, price: 499 },
    ],
  },
];

export const mockInternalUsers= [
  {
    id: 'int-1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@superadmin.com',
    role: 'developer',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2024-10-26T14:30:00Z',
  },
  {
    id: 'int-2',
    name: 'Priya Patel',
    email: 'priya.patel@superadmin.com',
    role: 'support',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2024-10-26T12:15:00Z',
  },
  {
    id: 'int-3',
    name: 'Amit Kumar',
    email: 'amit.kumar@superadmin.com',
    role: 'sales',
    status: 'active',
    mfaEnabled: false,
    lastLogin: '2024-10-25T16:45:00Z',
  },
  {
    id: 'int-4',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@superadmin.com',
    role: 'finance',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2024-10-26T09:00:00Z',
  },
];

export const mockPartnerRequests = [
  {
    id: 'req-001',
    partnerId: 'org-partner-1',
    partnerName: 'TechVision Partners',
    type: 'increase-users',
    requestedUsers: 500,
    justification: 'Secured 3 new enterprise clients requiring immediate onboarding',
    status: 'pending',
    createdAt: '2024-10-25T10:30:00Z',
  },
  {
    id: 'req-002',
    partnerId: 'org-partner-2',
    partnerName: 'GlobalSoft Solutions',
    type: 'add-subpartner',
    justification: 'Expanding to Chennai region with new distribution partner',
    status: 'pending',
    createdAt: '2024-10-24T14:00:00Z',
  },
  {
    id: 'req-003',
    partnerId: 'org-partner-1',
    partnerName: 'TechVision Partners',
    type: 'upgrade-tier',
    justification: 'Requesting upgrade to Enterprise tier for additional features',
    status: 'approved',
    createdAt: '2024-10-20T09:00:00Z',
    approvedBy: 'admin@superadmin.com',
    approvedAt: '2024-10-21T11:30:00Z',
  },
  {
    id: 'req-004',
    partnerId: 'org-partner-3',
    partnerName: 'InnovateTech Inc',
    type: 'increase-users',
    requestedUsers: 200,
    justification: 'Seasonal demand increase',
    status: 'rejected',
    createdAt: '2024-10-18T16:00:00Z',
    rejectedReason: 'Outstanding payment pending',
  },
];

export const mockPaymentLogs = [
  {
    id: 'pay-001',
    organizationId: 'org-partner-2',
    invoiceId: 'inv-002',
    amount: 1498500,
    method: 'bank-transfer',
    currency: 'INR',
    timestamp: '2024-10-22T10:30:00Z',
    status: 'success',
    transactionId: 'TXN2024102201',
    gateway: 'HDFC Bank',
  },
  {
    id: 'pay-002',
    organizationId: 'org-partner-1',
    invoiceId: 'inv-001',
    amount: 1500000,
    method: 'wallet',
    currency: 'INR',
    timestamp: '2024-10-20T14:15:00Z',
    status: 'success',
    transactionId: 'WLT2024102001',
  },
  {
    id: 'pay-003',
    organizationId: 'org-partner-3',
    invoiceId: 'inv-003',
    amount: 249500,
    method: 'upi',
    currency: 'INR',
    timestamp: '2024-10-15T16:45:00Z',
    status: 'failed',
    transactionId: 'UPI2024101501',
    gateway: 'Razorpay',
  },
];

export const mockWalletTransactions = [
  {
    id: 'wlt-001',
    organizationId: 'org-partner-1',
    type: 'credit',
    amount: 2000000,
    balance: 500000,
    description: 'Wallet top-up via bank transfer',
    timestamp: '2024-10-15T10:00:00Z',
  },
  {
    id: 'wlt-002',
    organizationId: 'org-partner-1',
    type: 'debit',
    amount: 1500000,
    balance: 500000,
    description: 'Payment for invoice INV-001',
    timestamp: '2024-10-20T14:15:00Z',
  },
  {
    id: 'wlt-003',
    organizationId: 'org-partner-2',
    type: 'credit',
    amount: 500000,
    balance: 250000,
    description: 'Bonus credit for Q3 performance',
    timestamp: '2024-10-01T09:00:00Z',
  },
];

export const mockPartnerIncentives = [
  {
    id: 'inc-001',
    partnerId: 'org-partner-1',
    type: 'commission',
    amount: 299800,
    description: 'Q3 2024 Commission - 20% on ₹14.99L sales',
    status: 'paid',
    dueDate: '2024-10-31',
    paidAt: '2024-10-25T10:00:00Z',
  },
  {
    id: 'inc-002',
    partnerId: 'org-partner-2',
    type: 'bonus',
    amount: 100000,
    description: 'Milestone bonus: 1500+ users activated',
    status: 'pending',
    dueDate: '2024-11-15',
  },
  {
    id: 'inc-003',
    partnerId: 'org-partner-1',
    type: 'milestone',
    amount: 500000,
    description: 'Enterprise tier achievement bonus',
    status: 'pending',
    dueDate: '2024-11-30',
  },
];

export const mockSecurityEvents = [
  {
    id: 'sec-001',
    userId: 'int-1',
    email: 'rahul.sharma@superadmin.com',
    event: 'login',
    ipAddress: '192.168.1.100',
    location: 'Mumbai, India',
    timestamp: '2024-10-26T14:30:00Z',
    status: 'success',
  },
  {
    id: 'sec-002',
    userId: 'int-2',
    email: 'priya.patel@superadmin.com',
    event: 'mfa-setup',
    ipAddress: '192.168.1.101',
    location: 'Bangalore, India',
    timestamp: '2024-10-26T12:15:00Z',
    status: 'success',
  },
  {
    id: 'sec-003',
    userId: 'unknown',
    email: 'hacker@example.com',
    event: 'login',
    ipAddress: '45.67.89.10',
    location: 'Unknown',
    timestamp: '2024-10-25T02:30:00Z',
    status: 'blocked',
  },
];

export const mockLegalDocuments= [
  {
    id: 'doc-001',
    title: 'Master Partnership Agreement',
    type: 'agreement',
    partnerId: 'org-partner-1',
    uploadedAt: '2024-02-15T10:00:00Z',
    uploadedBy: 'admin@superadmin.com',
    fileUrl: '/documents/mpa-techvision.pdf',
    status: 'active',
  },
  {
    id: 'doc-002',
    title: 'Non-Disclosure Agreement',
    type: 'nda',
    partnerId: 'org-partner-2',
    uploadedAt: '2024-03-10T14:30:00Z',
    uploadedBy: 'admin@superadmin.com',
    fileUrl: '/documents/nda-globalsoft.pdf',
    status: 'active',
  },
  {
    id: 'doc-003',
    title: 'Data Privacy Policy',
    type: 'policy',
    uploadedAt: '2024-01-01T09:00:00Z',
    uploadedBy: 'admin@superadmin.com',
    fileUrl: '/documents/privacy-policy.pdf',
    status: 'active',
  },
];

// Calculated metrics
export const calculateMetrics = () => {
  const totalPartners = mockOrganizations.filter(o => o.type === 'partner').length;
  const activePartners = mockOrganizations.filter(o => o.type === 'partner' && o.status === 'active').length;
  const totalSubPartners = mockOrganizations.filter(o => o.type === 'subpartner').length;
  const totalCustomers = mockOrganizations.filter(o => o.type === 'customer').length;

  const totalSeatsPurchased = mockSubscriptions.reduce((sum, s) => sum + s.seatsPurchased, 0);
  const totalSeatsAllocated = mockSubscriptions.reduce((sum, s) => sum + s.seatsAllocated, 0);
  const totalSeatsActivated = mockSubscriptions.reduce((sum, s) => sum + s.seatsActivated, 0);
  const totalSeatsIdle = totalSeatsAllocated - totalSeatsActivated;

  const totalMRR = mockSubscriptions
    .filter(s => s.status === 'active')
    .reduce((sum, s) => sum + s.price, 0);

  const expiringWithin30Days = mockSubscriptions.filter(s => {
    const daysToExpiry = Math.ceil((new Date(s.endDate).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));
    return daysToExpiry > 0 && daysToExpiry <= 30;
  }).length;

  return {
    totalPartners,
    activePartners,
    inactivePartners: totalPartners - activePartners,
    totalSubPartners,
    totalCustomers,
    totalSeatsPurchased,
    totalSeatsAllocated,
    totalSeatsActivated,
    totalSeatsIdle,
    totalMRR,
    expiringWithin30Days,
  };
};
