export interface UQC {
  code: string;
  description: string;
}

export const UQC_LIST: UQC[] = [
  { code: "BAG", description: "Bags" },
  { code: "BAL", description: "Bale" },
  { code: "BDL", description: "Bundles" },
  { code: "BKL", description: "Buckles" },
  { code: "BOU", description: "Billions of Units" },
  { code: "BOX", description: "Box" },
  { code: "BTL", description: "Bottles" },
  { code: "BUN", description: "Bunches" },
  { code: "CAN", description: "Cans" },
  { code: "CBM", description: "Cubic Meter" },
  { code: "CCM", description: "Cubic Centimeter" },
  { code: "CMS", description: "Centimeter" },
  { code: "CTN", description: "Cartons" },
  { code: "DOZ", description: "Dozen" },
  { code: "DRM", description: "Drum" },
  { code: "GGR", description: "Great Gross" },
  { code: "GMS", description: "Grams" },
  { code: "GRS", description: "Gross" },
  { code: "GYD", description: "Gross Yards" },
  { code: "KGS", description: "Kilograms" },
  { code: "KLR", description: "Kilolitre" },
  { code: "KME", description: "Kilometre" },
  { code: "MLT", description: "Millilitre" },
  { code: "MTR", description: "Meters" },
  { code: "MTS", description: "Metric Ton" },
  { code: "NOS", description: "Numbers" },
  { code: "PAC", description: "Packs" },
  { code: "PCS", description: "Pieces" },
  { code: "PRS", description: "Pairs" },
  { code: "QTL", description: "Quintal" },
  { code: "ROL", description: "Rolls" },
  { code: "SET", description: "Sets" },
  { code: "SQF", description: "Square Feet" },
  { code: "SQM", description: "Square Meters" },
  { code: "SQY", description: "Square Yards" },
  { code: "TBS", description: "Tablets" },
  { code: "TGM", description: "Ten Grams" },
  { code: "THD", description: "Thousands" },
  { code: "TON", description: "Tonnes" },
  { code: "TUB", description: "Tubes" },
  { code: "UGS", description: "US Gallons" },
  { code: "UNT", description: "Units" },
  { code: "YDS", description: "Yards" },
  { code: "OTH", description: "Others" },
];
